### ISSUE TITLE
I need information about how to preset MQTT with /provisioning/datasources/default.yml

### ISSUE THREAD

**Issue by Buronn** [grafana/mqtt-datasource#54]
Hello, I want to add this plugin as default, but I don't know what variables should be used to set it correctly:
```yml
datasources:
- name: MQTT
  access: websockets
  type: ammpio-mqtt-datasource
  websocket_url: wss://ws.mywebsocket.com/
  user: grafana
  pass: grafana
  isDefault: true
  editable: true
 ```
It works, but the WebSocket URL is not generated automatically, the password and the user are not generated either.

![image](https://user-images.githubusercontent.com/70445592/202591978-eafba3bd-4acc-4586-a802-08a05befdde2.png)
![image](https://user-images.githubusercontent.com/70445592/202592055-4356a58b-4173-43b0-8150-6664896f9ec5.png)
